fix: Get `make build` work again on a clean go modcache
Currently running `make build` on a clean go modcache ends with an error:

```
/tmp/instana-agent-operator/bin/controller-gen object paths="./..."
mocks/agent_status_manager_mock.go:17:2: no required module provides package go.uber.org/mock/gomock; to add it:
        go get go.uber.org/mock/gomock
Error: not all generators ran successfully
run `controller-gen object paths=./... -w` to see all available markers, or `controller-gen object paths=./... -h` for usage
make: *** [Makefile:115: generate] Error 1
```

This commit fixes that.

Signed-off-by: Ferenc Géczi <ferenc.geczi@ibm.com>